/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica3y4;

/**
 *
 * @author HP
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /** Creates new form FrmPrincipal */
    public FrmPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ber = new javax.swing.JButton();
        Num = new javax.swing.JTextField();
        Exito = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Poisson = new javax.swing.JButton();
        Geometrica = new javax.swing.JButton();
        Hipergeometrica = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Pobla = new javax.swing.JTextField();
        Exp = new javax.swing.JButton();
        Norm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ber.setText("BER");
        Ber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BerMouseClicked(evt);
            }
        });

        jLabel1.setText("NUMERO DE CASOS/MEDIA");

        jLabel2.setText("PROBABILIDAD/VARIANZA");

        Poisson.setText("POISSON");
        Poisson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PoissonMouseClicked(evt);
            }
        });

        Geometrica.setText("GEOMETRICA");
        Geometrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeometricaMouseClicked(evt);
            }
        });

        Hipergeometrica.setText("HIPERGEOMETRICA");
        Hipergeometrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HipergeometricaMouseClicked(evt);
            }
        });

        jLabel3.setText("POBLACION");

        Exp.setText("EXP");
        Exp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpMouseClicked(evt);
            }
        });

        Norm.setText("NORM");
        Norm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NormMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Geometrica)
                    .addComponent(Hipergeometrica)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ber)
                            .addComponent(Poisson)
                            .addComponent(Exp))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(120, 120, 120))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(117, 117, 117))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Exito, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Num, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pobla, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(156, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Norm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Ber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poisson))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Geometrica))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16)
                        .addComponent(Pobla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Hipergeometrica, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Exp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Norm)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BerMouseClicked
        // TODO add your handling code here:
        double a = Double.parseDouble(Num.getText());
        double b = Double.parseDouble(Exito.getText());
        int x = 0;
        int x1 = 1;
        int cont=0;
        double r;
        if(b<1){
            double Esperanza = a*b;
            double Varianza = a*b*(1-b);
            double Desviacion = Math.sqrt(Varianza);
         
          System.out.println("Esperanza: " + Esperanza + "Varianza: " + Varianza+ "Desviacion:  "+ Desviacion);
            int i;
          
          for(i=0; i<=99;i++ ){
              int v = Distribuciones.Bernoulli(b);
                
              cont++;
              if(v ==1){
                  System.out.println("Exito en numero" + cont + "es :" + v);
              } else {
                  System.out.println("Fracaso  en numero" + cont+ "es :" + v);
              }
          }
        } else {
          JOptionPane.showMessageDialog(null, "Error, la probabilidad debe de ser menor a 1");  
        }
        
    }//GEN-LAST:event_BerMouseClicked

    private void PoissonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PoissonMouseClicked
        // TODO add your handling code here:
        double a = Double.parseDouble(Num.getText());
        double b = Double.parseDouble(Exito.getText());
        int cont=0;
        if(b<1){
        double Esperanza = a*b;
        double Varianza = Esperanza;
        double Desviacion = Math.sqrt(Varianza);
        
        System.out.println("Esperanza: "+ Esperanza + "Varianza:  "+ Varianza+ "Desviacion:  "+ Desviacion);
        int i;
        for(i=0; i<= 99; i++){
            int v = Distribuciones.Poisson(b);
            cont++;
            if(v>=1){
            System.out.println("Numero de intento"+ cont + "Exito "+ v);
            } else {
             System.out.println("Numero de intento"+ cont + "Fracaso");
            }
        }
        } else{
            JOptionPane.showMessageDialog(null,"Error, la probabilidad debe de ser menor a 1");
        }
    }//GEN-LAST:event_PoissonMouseClicked

    private void GeometricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeometricaMouseClicked
        // TODO add your handling code here:
        double b = Double.parseDouble(Exito.getText());
        int cont = 0;
        if(b<1){
            double Esperanza = 1/b;
            double Varianza = 1-b/(b*b);
            if(Varianza>0){
            double Desviacion = Math.sqrt(Varianza);
            System.out.println("Esperanza: "+ Esperanza + "Varianza:  "+ Varianza+ "Desviacion:  "+ Desviacion);
            }
            else {
                Varianza = Varianza*-1;
                double Desviacion = Math.sqrt(Varianza);
                System.out.println("Esperanza: "+ Esperanza + "Varianza:  "+ Varianza+ "Desviacion:  "+ Desviacion);
            }
            
            int i = 0;
            
                do{
                    int v = Distribuciones.Geomtrica(b);
                    cont ++;
                    if(v==1){
                        System.out.println("Numero de intento"+ cont + "Exito "+ v);
                        i++;
                    } else {
                        
                    }
                } while(i !=1);
        } else{
            JOptionPane.showMessageDialog(null,"Error, la probabilidad debe de ser menor a 1");
        }
    }//GEN-LAST:event_GeometricaMouseClicked

    private void HipergeometricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HipergeometricaMouseClicked
        // TODO add your handling code here:
        double b = Double.parseDouble(Exito.getText());
        double n = Double.parseDouble(Num.getText());
        double m = Double.parseDouble(Pobla.getText());
        
         if(b<1){
             
            double Esperanza = n*b/m;
            double Varianza = ((m-n)/m-1)*(Esperanza)*(1-(b/m));
            double Desviacion = Math.sqrt(Varianza);
            System.out.println("Esperanza: "+ Esperanza + "Varianza:  "+ Varianza+ "Desviacion:  "+ Desviacion);
         }
    }//GEN-LAST:event_HipergeometricaMouseClicked

    private void ExpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpMouseClicked
        // TODO add your handling code here:double a = Double.parseDouble(Exito.getText());
        int i=0;
        int cont=0;
        double a = 0;
        if(a<1){
            
            double Esperanza = 1/a;
            double Varianza = 1/(a*a);
            double Desviacion = Math.sqrt(Varianza);
            System.out.println("Esperanza: "+ Esperanza + "Varianza:  "+ Varianza+ "Desviacion:  "+ Desviacion);
           for(i=0; i<=99; i++){
               double v = Distribuciones.Exponencial(a);
               cont++;
               System.out.println("Numero de intento"+ cont + "P "+ v);
               
           }
        } else{
            JOptionPane.showMessageDialog(null,"Error, la probabilidad debe de ser menor a 1");
        }
    }//GEN-LAST:event_ExpMouseClicked

    private void NormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NormMouseClicked
        // TODO add your handling code here:
        double a = Double.parseDouble(Exito.getText());
        double b = Double.parseDouble(Num.getText());
        int i=0;
        int cont =0;
        if(a<1){
            double Esperanza = a*b;
            double Varianza = a*b*(1-a);
            double Desviacion = Math.sqrt(Varianza);
            System.out.println("Esperanza: "+ Esperanza + "Varianza:  "+ Varianza+ "Desviacion:  "+ Desviacion);
            for(i=0; i<=99;i++){
                double x = Math.random();
                cont ++;
                System.out.println("Caso: "+ cont+ "es :"+ Distribuciones.Normal(x,a,b));
            }
        }
    }//GEN-LAST:event_NormMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ber;
    private javax.swing.JTextField Exito;
    private javax.swing.JButton Exp;
    private javax.swing.JButton Geometrica;
    private javax.swing.JButton Hipergeometrica;
    private javax.swing.JButton Norm;
    private javax.swing.JTextField Num;
    private javax.swing.JTextField Pobla;
    private javax.swing.JButton Poisson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
